#!/bin/sh -e

PROGNAME=$(basename $0)

version=${REDIS_VERSION:=2.6.12}
cli=redis-${version}/src/redis-cli
server=redis-${version}/src/redis-server

cd $(dirname $0)

runningpids() {
	pidof "$server" || true
}

getpid() {
	local port=$1
	pid=$(cat redis${port}.pid 2>/dev/null || true)
	[ -n "$pid" ] && echo $pid
	return 0
}

getrole() {
	local port=$1
	role=$("$cli" -p $port info  | awk -F: '$1 == "role" {printf "%s", $2}')
	# Work around carriage return in redis-cli output
	if echo $role | grep -q master; then
		echo master
	else
		echo slave
	fi

}

alive() {
	local port=$1
	pid=$(getpid $port)
	for running in $(runningpids); do
		if [ $running = "$pid" ]; then
			return 0
		fi
	done
	return 1
}

setup() {
	if [ "${version}" = "unstable" ]; then
		if [ ! -d "redis-${version}" ]; then
			git clone git://github.com/antirez/redis "redis-${version}"
		fi
	else
		if [ ! -e "dist/redis-${version}.tar.gz" ]; then
			mkdir -p dist
			wget -O "dist/redis-${version}.tar.gz" "http://redis.googlecode.com/files/redis-${version}.tar.gz"
		fi

		if [ ! -d "redis-${version}" ]; then
			tar -xzf "dist/redis-${version}.tar.gz"
		fi
	fi

	if [ ! -x "$server" ]; then
		( cd "redis-${version}" && make )
	fi

	template=$(cat <<EOF
daemonize yes
pidfile ./redisSED_PORT_SED.pid
port SED_PORT_SED

loglevel notice
logfile stdout
syslog-enabled yes
syslog-ident redis

databases 16

save 900 1
save 300 10
save 60 10000
rdbcompression yes
dbfilename dumpSED_PORT_SED.rdb
dir ./

slave-serve-stale-data yes
slave-priority 100

appendonly yes
appendfilename appendonlySED_PORT_SED.aof
appendfsync everysec
no-appendfsync-on-rewrite no
auto-aof-rewrite-percentage 100
auto-aof-rewrite-min-size 64mb
EOF
	)

	for port in 6380 6381 6382; do
		[ -e redis${port}.conf ] || echo "$template" | sed -e "s/SED_PORT_SED/${port}/g" > redis${port}.conf
	done
}

stop() {
	local ports="$*"
	ports=${ports:=6380 6381 6382}
	for port in $ports; do
		if [ $port != 6380 -a $port != 6381 -a $port != 6382 ]; then
			echo "$PROGNAME: error: only ports 6380, 6381 and 6382 are supported"
			exit 1
		fi
		if alive $port; then
			echo "Stopping redis-server on port $port"
			kill $(getpid $port)
			while alive $port; do sleep 0.1; done
		else
			echo "Already stopped redis-server on port $port"
		fi
	done
}

case "$1" in
	'')
		setup
		echo "Redis downloaded, built and configured"
		;;
	wipe)
		stop
		echo "Wiping configuration and persistent state"
		rm -frv *.aof *.rdb *.conf
		;;
	start)
		setup
		shift
		ports="$*"
		ports=${ports:=6380 6381 6382}
		for port in $ports; do
			if [ $port != 6380 -a $port != 6381 -a $port != 6382 ]; then
				echo "error: only ports 6380, 6381 and 6382 are supported"
				exit 1
			fi
			if ! alive $port; then
				echo "Starting redis-server on port $port"
				"$server" redis${port}.conf
			else
				echo "Already running redis-server on port $port"
			fi
		done
		;;
	stop)
		setup
		shift
		stop $*
		;;
	status)
		setup
		shift
		ports="$*"
		ports=${ports:=6380 6381 6382}
		status=0
		for port in $ports; do
			if alive $port; then
				echo "redis-server up on port $port ($(getrole $port))"
			else
				echo "redis-server down on port $port"
				status=1
			fi
		done
		exit $status
		;;
	*)
		echo 'usage: $PROGNAME [{start|stop|status|wipe} [port ...]]' 1>&2
		echo
		cat <<EOF
The script always makes sure that redis has been downloaded, built and
configured. Then an action (start, stop, status) is performed if specified.
If no action is specified, just the download, build and configure are
performed.

If no port numbers are specified for an action, then 6380, 6381 and 6382 are
assumed. Otherwise the actions are limited to the ports specified.

The wipe action stops all instances and then deletes all configuration and
persistent state.
EOF
		;;
esac
